basePath: /
definitions:
  todos.Todo:
    properties:
      complete:
        example: false
        type: boolean
      id:
        example: 1
        type: integer
      name:
        example: Cuci Baju
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Project 1 Kampus Merdeka X Hacktiv8 API Docs
  version: "1.0"
paths:
  /todos:
    delete:
      consumes:
      - application/json
      description: Delete Data Todos
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Delete Data Todos
    get:
      consumes:
      - application/json
      description: Get All Todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/todos.Todo'
            type: array
      summary: Get All Data Todos
    post:
      consumes:
      - application/json
      description: Post New Data Todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/todos.Todo'
      summary: Post New Data Todos
    put:
      consumes:
      - application/json
      description: Edit Data Todos
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Put Edit Data Todos
swagger: "2.0"
